### ISSUE TITLE
Issue when dissocing a header

### ISSUE THREAD

**Issue by ddossot** [ztellman/aleph#147]
Using 0.4.0-SNAPSHOT, if I call:

    (dissoc (:headers req) "host")

with `req` being a aleph server request, I get:
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map$Entry
	at clojure.lang.APersistentMap$KeySeq.first(APersistentMap.java:154)
	at clojure.lang.PersistentHashSet.create(PersistentHashSet.java:45)
	at clojure.core$set.invoke(core.clj:3782)
	at aleph.http.core.HeaderMap.keys_STAR_(core.clj:99)
	at aleph.http.core.HeaderMap.seq(core.clj:92)
	at clojure.lang.RT.seqFrom(RT.java:491)
	at clojure.lang.RT.seq(RT.java:486)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$print_map.invoke(core_print.clj:207)
	at clojure.core$fn__5482.invoke(core_print.clj:211)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at clojure.core$pr_on.invoke(core.clj:3392)
	at clojure.core$pr.invoke(core.clj:3404)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$pr.doInvoke(core.clj:3410)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$print.doInvoke(core.clj:3449)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:624)```
	at clojure.core$print_str.doInvoke(core.clj:4391)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at ub_api_specs.proxy$build_forwarded_request.invoke(proxy.clj:54)
	at ub_api_specs.proxy$api_v3_proxy.invoke(proxy.clj:71)
	at aleph.http.server$wrap_stream__GT_input_stream$fn__5455.invoke(server.clj:394)
	at aleph.http.server$handle_request$fn__5379$f__399__auto____5380.invoke(server.clj:152)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:49)
	at java.lang.Thread.run(Thread.java:745)
```
If I clone the headers map before calling dissoc, life's peachy.

**Comment by ztellman** [comment]
This was fixed in #145, but I hadn't redeployed a snapshot yet.  I just did, please confirm that this fixes your issue, or reopen the issue.

**Comment by ddossot** [comment]
Yes, the latest snapshot works perfectly, thank you and sorry for the duplicate :blush:

**Comment by ztellman** [comment]
Ha, no worries.  I'm just glad this got caught before the release.
