### ISSUE TITLE
http client keeps using closed persistent connection

### ISSUE THREAD

**Issue by pbwolf** [ztellman/aleph#194]
The following little web-client program (using aleph "0.4.1-beta3") sends several requests to the same web server.  It receives some good responses, the last of which has a "Connection: close" header; and then a "connection was closed" exception upon the next request.

The problem does not occur if the program uses connection-pool connection-options `{:keep-alive? false}`.

Could Aleph's HTTP client close a persistent connection upon receipt of a response with a "Connection: close" header?

Here is the program's output (it shows a request sequence number, and size of response body byte array, and selected response headers):
```
Received 27 66328 {}
Sending request 28
Received 28 66328 {}
Sending request 29
Received 29 66328 {}
Sending request 30
Received 30 66328 {connection close}
Sending request 31
Exception in thread "main" clojure.lang.ExceptionInfo: connection was closed {:request {:user-info nil, :pool #object[io.aleph.dirigiste.Pool 0x53833291 "io.aleph.dirigiste.Pool@53833291"], :as :byte-array, :server-port ..., :uri ..., :server-name ..., :query-string ..., :scheme :http, :request-method :get}}
    at clojure.core$ex_info.invoke(core.clj:4593)
    at aleph.http.client$http_connection$fn__6546$fn__6558$fn__6561.invoke(client.clj:329)
    at manifold.deferred$eval1171$chain_SINGLEQUOTE____1192.invoke(deferred.clj:750)
    at aleph.http.client$http_connection$fn__6546$fn__6558.invoke(client.clj:325)
    at aleph.http.client_middleware$wrap_exceptions$fn__6262$fn__6272.invoke(client_middleware.clj:176)
    at manifold.deferred$eval1171$chain_SINGLEQUOTE____1192.invoke(deferred.clj:750)
    at aleph.http.client_middleware$wrap_exceptions$fn__6262.invoke(client_middleware.clj:176)
    at aleph.http.client_middleware$wrap_request_timing$fn__6370.invoke(client_middleware.clj:419)
    at aleph.http.client_middleware$wrap_request$fn__6461.invoke(client_middleware.clj:532)
    at aleph.http$eval6630$request__6636$fn__6638$fn__6639$fn__6642.invoke(http.clj:235)
    at manifold.deferred$eval1171$chain_SINGLEQUOTE____1192.invoke(deferred.clj:768)
    at aleph.http$eval6630$request__6636$fn__6638$fn__6639.invoke(http.clj:221)
    at manifold.deferred$eval1171$chain_SINGLEQUOTE____1192.invoke(deferred.clj:750)
    at aleph.http$eval6630$request__6636$fn__6638.invoke(http.clj:206)
    at aleph.http$eval6630$request__6636.invoke(http.clj:196)
    at aleph.http$req.invoke(http.clj:272)
    at clojure.core$partial$fn__4527.invoke(core.clj:2494)
    at giblet.poughkeepsie$_main.invoke(poughkeepsie.clj:10)
...
```
Here is the program:

```
(ns giblet.poughkeepsie
  (:require [aleph.http :as http]))
(defn -main
  [url]
  (let [pool (http/connection-pool
              {:connections-per-host 1
               :connection-options {:keep-alive? true}})]
    (dotimes [n 42]
      (println "Sending request" n)
      (let [hr (deref (http/get url
                                {:pool pool
                                 :as :byte-array
                                 :query-params {"n" (str n)}}))]
        (println "Received" n
                 (alength (:body hr))
                 (select-keys (:headers hr) ["connection"]))))))
```

**Comment by ztellman** [comment]
I'll need to double check, but my understanding is that it's the server's
responsibility to close the connection. I could, however, not put those
connections back into the pool, that seems to invite this sort of problem.
