### ISSUE TITLE
Exception on very simple example 

### ISSUE THREAD

**Issue by rhacker** [ztellman/aleph#203]
I have a very simple example but it doesn't seem to work
code
```clojure
(ns backend.main
  (:require
   [com.stuartsierra.component :as component]
   [clojure.pprint :refer [pprint]]
   [aleph.http :as http]
   [compojure.core :as compojure :refer [GET]]
   [ring.middleware.params :as params]
   [compojure.route :as route]
   [compojure.response :refer [Renderable]]))

(defn help [req]
  {:status 200
   :headers {"content-type" "text/plain"}
   :body "Test body"})

(def handler
  (params/wrap-params
   (compojure/routes
    (GET "/hello" [] help)
    (route/not-found "No such page."))))


(defn -main []
  (http/start-server handler {:port 3000})  )
```

Then I got this exception when I request using `curl http://localhost:3000`
```sh
backend.main=> Jan 01, 2016 11:18:19 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: io.netty.handler.codec.http.HttpServerCodec.handlerAdded() has thrown an exception; removed.
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:501)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded(DefaultChannelPipeline.java:482)
	at io.netty.channel.DefaultChannelPipeline.addLast0(DefaultChannelPipeline.java:146)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:129)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:120)
	at aleph.http.server$pipeline_builder$fn__15196.invoke(server.clj:385)
	at aleph.netty$pipeline_initializer$reify__14038.channelRegistered(netty.clj:478)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:162)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:148)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:734)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: tried to access method io.netty.channel.DefaultChannelPipeline.generateName(Lio/netty/channel/ChannelHandler;)Ljava/lang/String; from class io.netty.channel.ChannelHandlerAppender
	at io.netty.channel.ChannelHandlerAppender.handlerAdded(ChannelHandlerAppender.java:190)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:488)
	... 17 more
```

**Comment by ztellman** [comment]
Can you give me the output of 'lein deps :tree'? I suspect a version mismatch somewhere.

**Comment by rhacker** [comment]
@ztellman Here is the result of `lein deps :tree`
```sh
 [aero "0.1.3"]
 [aleph "0.4.0"]
   [io.aleph/dirigiste "0.1.0"]
   [io.netty/netty-all "4.1.0.Beta4"]
 [bidi "1.24.0"]
 [byte-streams "0.2.0"]
   [clj-tuple "0.2.1"]
   [primitive-math "0.1.4"]
 [clojure-complete "0.2.3" :exclusions [[org.clojure/clojure]]]
 [clojurewerkz/elastisch "2.2.0-rc1" :exclusions [[com.fasterxml.jackson.dataformat/jackson-dataformat-smile] [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor] [org.apache.httpcomponents/httpclient] [org.apache.httpcomponents/httpcore] [com.fasterxml.jackson.core/jackson-core]]]
   [clj-http "2.0.0" :exclusions [[org.clojure/clojure]]]
     [org.apache.httpcomponents/httpmime "4.5" :exclusions [[org.clojure/clojure]]]
   [clojurewerkz/support "1.1.0" :exclusions [[com.google.guava/guava]]]
   [org.elasticsearch/elasticsearch "1.7.3"]
     [org.apache.lucene/lucene-analyzers-common "4.10.4"]
     [org.apache.lucene/lucene-core "4.10.4"]
     [org.apache.lucene/lucene-grouping "4.10.4"]
     [org.apache.lucene/lucene-highlighter "4.10.4"]
     [org.apache.lucene/lucene-join "4.10.4"]
     [org.apache.lucene/lucene-memory "4.10.4"]
     [org.apache.lucene/lucene-misc "4.10.4"]
     [org.apache.lucene/lucene-queries "4.10.4"]
     [org.apache.lucene/lucene-queryparser "4.10.4"]
     [org.apache.lucene/lucene-sandbox "4.10.4" :exclusions [[jakarta-regexp]]]
     [org.apache.lucene/lucene-spatial "4.10.4"]
       [com.spatial4j/spatial4j "0.4.1"]
     [org.apache.lucene/lucene-suggest "4.10.4"]
     [org.yaml/snakeyaml "1.12"]
 [com.cognitect/transit-clj "0.8.285"]
   [com.cognitect/transit-java "0.8.311"]
     [org.msgpack/msgpack "0.6.10"]
       [com.googlecode.json-simple/json-simple "1.1.1" :exclusions [[junit]]]
       [org.javassist/javassist "3.18.1-GA"]
 [com.cognitect/transit-cljs "0.8.232"]
   [com.cognitect/transit-js "0.8.755"]
 [com.flyingmachine/datomic-junk "0.2.1"]
 [com.mchange/c3p0 "0.9.5-pre8"]
   [com.mchange/mchange-commons-java "0.2.7"]
 [com.stuartsierra/component "0.3.1"]
   [com.stuartsierra/dependency "0.2.0"]
 [compojure "1.4.0"]
   [clout "2.1.2"]
   [medley "0.6.0"]
   [org.clojure/tools.macro "0.1.5"]
   [ring/ring-codec "1.0.0"]
   [ring/ring-core "1.4.0"]
     [commons-fileupload "1.3.1"]
     [crypto-equality "1.0.0"]
     [crypto-random "1.2.0"]
     [org.clojure/tools.reader "0.9.1"]
 [joplin.cassandra "0.3.5" :exclusions [[org.slf4j/slf4j-api]]]
   [clojurewerkz/cassaforte "2.0.2"]
     [cc.qbits/hayt "2.1.0"]
       [cc.qbits/commons "0.1.0"]
       [cc.qbits/pod "0.2.0"]
       [org.apache.commons/commons-lang3 "3.3.2"]
     [com.datastax.cassandra/cassandra-driver-core "2.1.6"]
       [com.codahale.metrics/metrics-core "3.0.2"]
       [io.netty/netty-handler "4.0.27.Final"]
         [io.netty/netty-buffer "4.0.27.Final"]
           [io.netty/netty-common "4.0.27.Final"]
         [io.netty/netty-codec "4.0.27.Final"]
         [io.netty/netty-transport "4.0.27.Final"]
     [com.datastax.cassandra/cassandra-driver-dse "2.1.6"]
 [joplin.core "0.3.5"]
   [clj-time "0.11.0"]
     [joda-time "2.8.2"]
   [org.clojure/java.classpath "0.2.3"]
   [ragtime/ragtime.core "0.5.2"]
 [joplin.datomic "0.3.5" :exclusions [[org.slf4j/slf4j-api]]]
   [com.datomic/datomic-free "0.9.5344" :exclusions [[joda-time]]]
     [com.datomic/datomic-lucene-core "3.3.0"]
     [com.google.guava/guava "18.0"]
     [com.h2database/h2 "1.3.171"]
     [commons-codec "1.5"]
     [org.apache.tomcat/tomcat-jdbc "7.0.27" :exclusions [[commons-logging]]]
       [org.apache.tomcat/tomcat-juli "7.0.27"]
     [org.clojure/tools.cli "0.2.2" :exclusions [[org.clojure/clojure]]]
     [org.codehaus.janino/commons-compiler-jdk "2.6.1"]
       [org.codehaus.janino/commons-compiler "2.6.1"]
     [org.fressian/fressian "0.6.5"]
     [org.hornetq/hornetq-server "2.3.17.Final"]
       [org.hornetq/hornetq-commons "2.3.17.Final"]
       [org.hornetq/hornetq-core-client "2.3.17.Final"]
         [org.jgroups/jgroups "3.2.12.Final"]
       [org.hornetq/hornetq-journal "2.3.17.Final"]
       [org.jboss.logging/jboss-logging "3.1.0.GA"]
     [org.slf4j/jcl-over-slf4j "1.7.7"]
     [org.slf4j/jul-to-slf4j "1.7.7"]
     [org.slf4j/log4j-over-slf4j "1.7.7" :scope "runtime"]
     [org.slf4j/slf4j-nop "1.7.7"]
 [joplin.dynamodb "0.3.5"]
   [com.taoensso/faraday "1.8.0"]
     [com.amazonaws/aws-java-sdk-dynamodb "1.9.39" :exclusions [[joda-time]]]
       [com.amazonaws/aws-java-sdk-core "1.9.39"]
         [com.fasterxml.jackson.core/jackson-databind "2.3.2"]
           [com.fasterxml.jackson.core/jackson-annotations "2.3.0"]
         [commons-logging "1.1.3"]
       [com.amazonaws/aws-java-sdk-s3 "1.9.39"]
         [com.amazonaws/aws-java-sdk-kms "1.9.39"]
     [com.taoensso/encore "2.18.0"]
     [com.taoensso/nippy "2.9.1"]
       [net.jpountz.lz4/lz4 "1.3"]
       [org.iq80.snappy/snappy "0.3"]
       [org.tukaani/xz "1.5"]
 [joplin.elasticsearch "0.3.5" :exclusions [[org.antlr/antlr-runtime]]]
 [joplin.hive "0.3.5" :exclusions [[org.codehaus.janino/commons-compiler] [org.apache.avro/avro] [org.apache.curator/curator-framework] [commons-logging] [log4j] [commons-httpclient] [org.slf4j/slf4j-log4j12] [org.slf4j/slf4j-api] [org.xerial.snappy/snappy-java]]]
   [commons-io "2.4"]
   [org.apache.hadoop/hadoop-client "2.7.1"]
     [org.apache.hadoop/hadoop-annotations "2.7.1" :exclusions [[jdk.tools]]]
     [org.apache.hadoop/hadoop-common "2.7.1" :exclusions [[javax.servlet/servlet-api] [commons-logging/commons-logging-api] [jetty/org.mortbay.jetty] [org.mortbay.jetty/jetty] [org.mortbay.jetty/jetty-util] [org.mortbay.jetty/servlet-api-2.5] [com.sun.jersey/jersey-core] [com.sun.jersey/jersey-json] [com.sun.jersey/jersey-server] [org.eclipse.jdt/core] [org.apache.avro/avro-ipc] [net.sf.kosmosfs/kfs] [net.java.dev.jets3t/jets3t] [com.jcraft/jsch]]]
       [com.google.code.findbugs/jsr305 "3.0.0"]
       [com.google.code.gson/gson "2.2.4"]
       [com.google.protobuf/protobuf-java "2.5.0"]
       [commons-cli "1.2"]
       [commons-collections "3.2.1"]
       [commons-configuration "1.6"]
         [commons-beanutils/commons-beanutils-core "1.8.0"]
         [commons-digester "1.8"]
           [commons-beanutils "1.7.0"]
       [commons-lang "2.6"]
       [commons-net "3.1"]
       [javax.servlet.jsp/jsp-api "2.1" :scope "runtime"]
       [org.apache.commons/commons-math3 "3.1.1"]
       [org.apache.curator/curator-client "2.7.1"]
       [org.apache.hadoop/hadoop-auth "2.7.1"]
         [org.apache.directory.server/apacheds-kerberos-codec "2.0.0-M15" :exclusions [[org.apache.directory.api/api-asn1-ber] [org.apache.directory.api/api-i18n] [org.apache.directory.api/api-ldap-model] [net.sf.ehcache/ehcache-core]]]
           [org.apache.directory.api/api-asn1-api "1.0.0-M20"]
           [org.apache.directory.api/api-util "1.0.0-M20"]
           [org.apache.directory.server/apacheds-i18n "2.0.0-M15"]
       [org.apache.htrace/htrace-core "3.1.0-incubating"]
       [org.codehaus.jackson/jackson-core-asl "1.9.13"]
       [org.codehaus.jackson/jackson-mapper-asl "1.9.13"]
       [xmlenc "0.52"]
     [org.apache.hadoop/hadoop-hdfs "2.7.1" :exclusions [[commons-daemon] [org.apache.avro/avro] [org.mortbay.jetty/jetty] [com.sun.jersey/jersey-core] [com.sun.jersey/jersey-server] [javax.servlet/servlet-api]]]
       [org.fusesource.leveldbjni/leveldbjni-all "1.8"]
       [org.mortbay.jetty/jetty-util "6.1.26"]
       [xerces/xercesImpl "2.9.1"]
         [xml-apis "1.3.04"]
     [org.apache.hadoop/hadoop-mapreduce-client-app "2.7.1" :exclusions [[javax.servlet/servlet-api] [org.apache.hadoop/hadoop-yarn-server-nodemanager] [org.apache.hadoop/hadoop-yarn-server-web-proxy] [org.apache.hadoop/hadoop-annotations] [com.google.inject.extensions/guice-servlet] [junit] [org.apache.avro/avro] [jline] [io.netty/netty]]]
       [org.apache.hadoop/hadoop-mapreduce-client-common "2.7.1"]
         [org.apache.hadoop/hadoop-yarn-client "2.7.1"]
         [org.apache.hadoop/hadoop-yarn-server-common "2.7.1"]
       [org.apache.hadoop/hadoop-mapreduce-client-shuffle "2.7.1"]
     [org.apache.hadoop/hadoop-mapreduce-client-core "2.7.1" :exclusions [[junit] [com.google.inject/guice] [com.sun.jersey.jersey-test-framework/jersey-test-framework-grizzly2] [com.sun.jersey/jersey-server] [com.sun.jersey.contribs/jersey-guice] [org.apache.avro/avro] [org.apache.hadoop/hadoop-annotations] [com.google.inject.extensions/guice-servlet] [com.sun.jersey/jersey-json] [io.netty/netty]]]
       [org.apache.hadoop/hadoop-yarn-common "2.7.1"]
         [com.sun.jersey/jersey-client "1.9"]
         [com.sun.jersey/jersey-core "1.9"]
         [javax.servlet/servlet-api "2.5"]
         [javax.xml.bind/jaxb-api "2.2.2"]
           [javax.xml.stream/stax-api "1.0-2"]
         [org.codehaus.jackson/jackson-jaxrs "1.9.13"]
         [org.codehaus.jackson/jackson-xc "1.9.13"]
     [org.apache.hadoop/hadoop-mapreduce-client-jobclient "2.7.1" :exclusions [[junit] [org.apache.avro/avro] [org.apache.hadoop/hadoop-annotations] [com.google.inject.extensions/guice-servlet] [io.netty/netty]]]
     [org.apache.hadoop/hadoop-yarn-api "2.7.1" :exclusions [[org.apache.hadoop/hadoop-annotations] [com.google.inject/guice] [com.sun.jersey.jersey-test-framework/jersey-test-framework-grizzly2] [com.sun.jersey/jersey-server] [com.sun.jersey.contribs/jersey-guice] [com.google.inject.extensions/guice-servlet] [org.apache.avro/avro] [com.sun.jersey/jersey-core] [com.sun.jersey/jersey-json] [io.netty/netty]]]
   [org.apache.hive/hive-exec "1.2.1"]
     [jline "2.12"]
     [log4j/apache-log4j-extras "1.2.17"]
     [org.antlr/ST4 "4.0.4"]
     [org.antlr/antlr-runtime "3.4"]
       [antlr "2.7.7"]
       [org.antlr/stringtemplate "3.2.1"]
     [org.apache.ant/ant "1.9.1"]
       [org.apache.ant/ant-launcher "1.9.1"]
     [org.apache.calcite/calcite-avatica "1.2.0-incubating" :exclusions [[org.hsqldb/hsqldb] [com.fasterxml.jackson.core/jackson-databind] [com.fasterxml.jackson.core/jackson-annotations] [com.fasterxml.jackson.core/jackson-core]]]
     [org.apache.calcite/calcite-core "1.2.0-incubating" :exclusions [[org.hsqldb/hsqldb] [com.fasterxml.jackson.core/jackson-databind] [com.fasterxml.jackson.core/jackson-annotations] [com.fasterxml.jackson.core/jackson-core]]]
       [net.hydromatic/eigenbase-properties "1.1.5"]
       [org.apache.calcite/calcite-linq4j "1.2.0-incubating"]
       [org.codehaus.janino/janino "2.7.6"]
       [org.pentaho/pentaho-aggdesigner-algorithm "5.1.5-jhyde"]
     [org.apache.commons/commons-compress "1.4.1"]
     [org.apache.curator/apache-curator "2.6.0" :extension "pom"]
     [org.apache.hive/hive-ant "1.2.1"]
       [org.apache.velocity/velocity "1.5"]
         [oro "2.0.8"]
     [org.apache.hive/hive-metastore "1.2.1"]
       [com.jolbox/bonecp "0.8.0.RELEASE"]
       [commons-dbcp "1.4"]
       [commons-pool "1.5.4"]
       [javax.jdo/jdo-api "3.0.1"]
         [javax.transaction/jta "1.1"]
       [org.apache.derby/derby "10.10.2.0"]
       [org.datanucleus/datanucleus-api-jdo "3.2.6"]
       [org.datanucleus/datanucleus-rdbms "3.2.9"]
     [org.apache.hive/hive-shims "1.2.1"]
       [org.apache.hive.shims/hive-shims-0.20S "1.2.1" :scope "runtime"]
       [org.apache.hive.shims/hive-shims-0.23 "1.2.1" :scope "runtime"]
         [org.apache.hadoop/hadoop-yarn-server-resourcemanager "2.6.0" :scope "runtime" :exclusions [[javax.servlet/servlet-api]]]
           [com.google.inject.extensions/guice-servlet "3.0"]
           [com.google.inject/guice "3.0"]
             [aopalliance "1.0"]
             [javax.inject "1"]
           [com.sun.jersey.contribs/jersey-guice "1.9"]
             [com.sun.jersey/jersey-server "1.9"]
           [com.sun.jersey/jersey-json "1.9" :exclusions [[stax/stax-api]]]
             [com.sun.xml.bind/jaxb-impl "2.2.3-1"]
           [org.apache.hadoop/hadoop-yarn-server-applicationhistoryservice "2.6.0" :scope "runtime"]
           [org.apache.hadoop/hadoop-yarn-server-web-proxy "2.6.0" :scope "runtime"]
             [org.mortbay.jetty/jetty "6.1.26" :scope "runtime" :exclusions [[org.mortbay.jetty/servlet-api]]]
           [org.codehaus.jettison/jettison "1.1" :exclusions [[stax/stax-api]]]
       [org.apache.hive.shims/hive-shims-common "1.2.1"]
       [org.apache.hive.shims/hive-shims-scheduler "1.2.1" :scope "runtime"]
     [org.apache.ivy/ivy "2.4.0"]
     [org.apache.thrift/libfb303 "0.9.2"]
     [org.codehaus.groovy/groovy-all "2.1.6"]
     [org.datanucleus/datanucleus-core "3.2.10"]
     [stax/stax-api "1.0.1"]
   [org.apache.hive/hive-jdbc "1.2.1"]
     [org.apache.hive/hive-common "1.2.1"]
       [org.json/json "20090211"]
     [org.apache.hive/hive-serde "1.2.1"]
       [com.twitter/parquet-hadoop-bundle "1.6.0"]
       [net.sf.opencsv/opencsv "2.3"]
     [org.apache.hive/hive-service "1.2.1" :exclusions [[org.apache.hive/hive-exec]]]
       [net.sf.jpam/jpam "1.1"]
       [org.eclipse.jetty.aggregate/jetty-all "7.6.0.v20120127"]
         [asm/asm-commons "3.1"]
           [asm/asm-tree "3.1"]
             [asm "3.1"]
         [javax.activation/activation "1.1"]
         [javax.mail/mail "1.4.1"]
         [org.apache.geronimo.specs/geronimo-annotation_1.0_spec "1.1.1"]
         [org.apache.geronimo.specs/geronimo-jaspic_1.0_spec "1.0"]
         [org.apache.geronimo.specs/geronimo-jta_1.1_spec "1.1.1"]
     [org.apache.httpcomponents/httpclient "4.4"]
     [org.apache.httpcomponents/httpcore "4.4"]
     [org.apache.thrift/libthrift "0.9.2"]
   [org.clojure/java.jdbc "0.4.2"]
 [joplin.jdbc "0.3.5"]
   [ragtime/ragtime.jdbc "0.5.2"]
     [resauce "0.1.0"]
 [joplin.zookeeper "0.3.5" :exclusions [[org.apache.curator/curator-framework] [org.apache.curator/curator-client]]]
   [curator "0.0.6"]
     [org.apache.curator/curator-recipes "2.8.0" :exclusions [[org.slf4j/slf4j-log4j12]]]
     [org.apache.curator/curator-x-discovery "2.8.0" :exclusions [[org.slf4j/slf4j-log4j12]]]
   [org.apache.zookeeper/zookeeper "3.4.7" :exclusions [[commons-codec] [com.sun.jmx/jmxri] [com.sun.jdmk/jmxtools] [javax.jms/jms] [org.slf4j/slf4j-log4j12] [log4j]]]
     [io.netty/netty "3.7.0.Final"]
     [org.slf4j/slf4j-api "1.6.1"]
   [zookeeper-clj "0.9.3" :exclusions [[org.apache.zookeeper/zookeeper] [log4j]]]
 [juxt.modular/co-dependency "0.3.0"]
 [manifold "0.1.1"]
   [riddley "0.1.10"]
 [org.clojure/clojure "1.7.0" :scope "provided"]
 [org.clojure/core.async "0.2.371" :scope "test"]
   [org.clojure/tools.analyzer.jvm "0.6.7" :scope "test"]
     [org.clojure/core.memoize "0.5.6" :scope "test"]
       [org.clojure/core.cache "0.6.3" :scope "test"]
         [org.clojure/data.priority-map "0.0.2" :scope "test"]
     [org.clojure/tools.analyzer "0.6.6" :scope "test"]
     [org.ow2.asm/asm-all "4.2" :scope "test"]
 [org.clojure/tools.logging "0.3.1"]
 [org.clojure/tools.namespace "0.2.10" :scope "test"]
 [org.clojure/tools.nrepl "0.2.10" :exclusions [[org.clojure/clojure]]]
 [org.omcljs/om "1.0.0-alpha29-SNAPSHOT"]
   [cljsjs/react-dom "0.14.3-1"]
   [cljsjs/react "0.14.3-0"]
 [org.postgresql/postgresql "9.4-1201-jdbc41"]
 [prismatic/schema "1.0.4"]
 [ring "1.4.0"]
   [ring/ring-devel "1.4.0"]
     [clj-stacktrace "0.2.8"]
     [ns-tracker "0.3.0"]
   [ring/ring-jetty-adapter "1.4.0"]
     [org.eclipse.jetty/jetty-server "9.2.10.v20150310"]
       [javax.servlet/javax.servlet-api "3.1.0"]
       [org.eclipse.jetty/jetty-http "9.2.10.v20150310"]
         [org.eclipse.jetty/jetty-util "9.2.10.v20150310"]
       [org.eclipse.jetty/jetty-io "9.2.10.v20150310"]
   [ring/ring-servlet "1.4.0"]
 [spyscope "0.1.5"]
 [yada "1.0.0"]
   [camel-snake-kebab "0.1.4" :exclusions [[org.clojure/clojure] [prismatic/schema] [com.stuartsierra/component]]]
   [cheshire "5.4.0" :exclusions [[org.clojure/clojure] [prismatic/schema] [com.stuartsierra/component]]]
     [com.fasterxml.jackson.core/jackson-core "2.4.4"]
     [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.4.4"]
     [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.4.4"]
     [tigris "0.1.1"]
   [hiccup "1.0.5" :exclusions [[org.clojure/clojure] [prismatic/schema] [com.stuartsierra/component]]]
   [json-html "0.3.1" :exclusions [[org.clojure/clojure] [prismatic/schema] [com.stuartsierra/component]]]
     [hiccups "0.3.0"]
     [org.clojure/clojurescript "0.0-2322"]
       [com.google.javascript/closure-compiler "v20140625"]
         [args4j "2.0.26"]
         [com.google.javascript/closure-compiler-externs "v20140625"]
       [org.clojure/data.json "0.2.3"]
       [org.clojure/google-closure-library "0.0-20140718-946a7d39"]
         [org.clojure/google-closure-library-third-party "0.0-20140718-946a7d39"]
       [org.mozilla/rhino "1.7R4"]
   [juxt/iota "0.1.2" :exclusions [[org.clojure/clojure] [prismatic/schema] [com.stuartsierra/component]]]
   [metosin/ring-swagger "0.20.2" :exclusions [[org.clojure/clojure] [prismatic/schema] [com.stuartsierra/component] [potemkin]]]
     [instar "1.0.10" :exclusions [[org.clojure/clojure] [com.keminglabs/cljx] [org.clojure/clojurescript]]]
     [metosin/ring-http-response "0.6.1"]
     [metosin/schema-tools "0.4.0"]
     [org.flatland/ordered "1.5.2"]
       [org.flatland/useful "0.9.0"]
     [org.tobereplaced/lettercase "1.0.0"]
     [prismatic/plumbing "0.4.2"]
       [de.kotka/lazymap "3.1.0" :exclusions [[org.clojure/clojure]]]
     [slingshot "0.12.2"]
   [potemkin "0.4.1" :exclusions [[org.clojure/clojure] [prismatic/schema] [com.stuartsierra/component] [riddley]]]
   [ring-basic-authentication "1.0.5" :exclusions [[org.clojure/clojure] [prismatic/schema] [com.stuartsierra/component]]]
     [org.clojure/data.codec "0.1.0"]
 [yesql "0.5.1"]
   [instaparse "1.4.1" :exclusions [[org.clojure/clojure]]]

```

**Comment by ztellman** [comment]
Hi, I'm sorry for having lost track of this issue.  The problem is that you're including two different versions of Netty, due to this dependency:

```clj
[joplin.cassandra "0.3.5" :exclusions [[org.slf4j/slf4j-api]]]
   [clojurewerkz/cassaforte "2.0.2"]
     [cc.qbits/hayt "2.1.0"]
       [cc.qbits/commons "0.1.0"]
       [cc.qbits/pod "0.2.0"]
       [org.apache.commons/commons-lang3 "3.3.2"]
     [com.datastax.cassandra/cassandra-driver-core "2.1.6"]
       [com.codahale.metrics/metrics-core "3.0.2"]
       [io.netty/netty-handler "4.0.27.Final"]
         [io.netty/netty-buffer "4.0.27.Final"]
           [io.netty/netty-common "4.0.27.Final"]
         [io.netty/netty-codec "4.0.27.Final"]
         [io.netty/netty-transport "4.0.27.Final"]
     [com.datastax.cassandra/cassandra-driver-dse "2.1.6"]
```

You'll need to explicitly exclude it.
