### ISSUE TITLE
ConcurrentHashMap-related errors

### ISSUE THREAD

**Issue by alvatar** [ztellman/aleph#218]
Hi,

I have this code:

```
(def channels (bus/event-bus))

(defn subscription-handler [req]
  (d/let-flow [conn (d/catch
                        (http/websocket-connection req)
                        (fn [_] nil))]
    (if-not conn
      non-websocket-request
      (d/let-flow [channel-id (s/take! conn)]
        ;(println "Subscribe: " channel-id)
        (s/connect
         (bus/subscribe channels channel-id)
         conn)))))

(defn notification-handler [req]
  (let [params (:params req)
        id (params "id")
        message (params "message")]
    ;(pprint (bus/topic->subscribers channels))
    ;(pprint (bus/downstream channels id))
    (if (bus/active? channels id)
      (let [result (bus/publish! channels id message)]
        (if (and @result (bus/active? channels id))
          {:status 200
           :headers {"content-type" "application/text"}
           :body "Ok"}
          {:status 200
           :headers {"content-type" "application/text"}
           :body "Not delivered"}))
      {:status 200
       :headers {"content-type" "application/text"}
       :body "No subscribers"})))
```

When running it (compiled uberjar), I get this error:

```
Exception in thread "dirigiste-pool-controller-0" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at io.aleph.dirigiste.Stats$UniformLongReservoirMap.toMap(Stats.java:114)
        at io.aleph.dirigiste.Pool.updateStats(Pool.java:233)
        at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:316)
        at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
        at io.aleph.dirigiste.Pool$1.run(Pool.java:377)
        at java.lang.Thread.run(Thread.java:745)
```

Then at first the server works well, but when opening many connections (in the order of 32k, using 2 client machines), I start getting these kind of errors:

```
Mar 07, 2016 7:37:20 AM clojure.tools.logging$eval1$fn__5 invoke
SEVERE: error in HTTP handler
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)
        at manifold.bus$event_bus$reify__13294.subscribe(bus.clj:97)
        at notifications_server.core$subscription_handler$fn__13372$fn__13376.invoke(core.clj:46)
        at manifold.deferred$fn__9253$chain___9274.invoke(deferred.clj:840)
        at manifold.deferred$fn__9253$subscribe__9254$fn__9259.invoke(deferred.clj:810)
        at manifold.deferred.Listener.onSuccess(deferred.clj:219)
        at manifold.deferred.Deferred$fn__9066$fn__9067.invoke(deferred.clj:396)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
        at manifold.executor$thread_factory$reify__8587$f__8588.invoke(executor.clj:36)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
```

And, to a lesser extent, these ones:

```
Mar 07, 2016 7:37:21 AM clojure.tools.logging$eval1$fn__5 invoke
SEVERE: error in deferred handler
java.util.concurrent.RejectedExecutionException
        at io.aleph.dirigiste.Executor.execute(Executor.java:332)
        at manifold.deferred.Deferred$fn__9066.invoke(deferred.clj:396)
        at manifold.deferred.Deferred.success(deferred.clj:396)
        at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:243)
        at manifold.deferred$success_BANG_.invoke(deferred.clj:240)
        at aleph.netty$wrap_future$reify__12255.operationComplete(netty.clj:184)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:407)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1042)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:679)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:657)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:601)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:70)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:133)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
```
Any idea if this is an issue in my code or a bug in Aleph? I became suspicious due to the apparent relation between the exception that shows up at the server boot time.

**Comment by ztellman** [comment]
The issue here is that your `id` is nil.  You should get a better error when this happens, but it's definitely a bug in your code.

**Comment by ztellman** [comment]
Sorry, I missed the second error.  That's harder for me to explain, you'd need to show me what sort of executor you're specifying for your server.

**Comment by alvatar** [comment]
The rest of the code is just a Compojure routing, I define no executor. I'm using [aleph "0.4.1-beta5"] and [manifold "0.1.2"]
Also, the first error happens just at boot time, before any request is made, so the null id issue shouldn't kick in yet.

**Comment by ztellman** [comment]
Sorry, I responded to this before my morning coffee, and overlooked two of the three errors.  

* The first error is because Dirigiste 0.1.2 was compiled with JDK 8 byte code by accident.  That will be resolved by adding `[io.aleph/dirigiste "0.1.3-alpha1"]` to your dependency list.
* The second exception is explained above.
* I'm fairly sure I know what the third error, and I'll have a fix for it presently.

**Comment by alvatar** [comment]
Thank you @ztellman!
One question related to the second point: if I'm sure that the client sends a message with an Id, what would be causing the `stream/take!` function to succeed and return a nil value? Is this expected in a way so that I have to set up a loop until the message is as expected or is it in all likelihood an error in the test client I'm using?

**Comment by ztellman** [comment]
`@(s/take! conn)` will return `nil` if the stream is closed before a message is received.  `@(s/stake! conn ::closed)` will return `::closed` if the stream is closed before a message is received.  Depending on the sorts of messages you're receiving, you can either just ignore nil messages, or check for an explicit "closed" value.

**Comment by alvatar** [comment]
Awesome! That clarifies a lot. Thank you!

**Comment by alvatar** [comment]
BTW, aleph, manifold et al. libraries are awesome!

**Comment by alvatar** [comment]
@ztellman, apparently just adding `[io.aleph/dirigiste "0.1.3-alpha1"]` doesn't fix it in my case. I can open a separate issue to track this if you prefer.

**Comment by ztellman** [comment]
@alvatar please do, and include the output of `java -version` at your terminal.

**Comment by alvatar** [comment]
Done. Thanks!
