### ISSUE TITLE
[WebSocket] CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:5

### ISSUE THREAD

**Issue by BorisKourt** [ztellman/aleph#221]
Hello,

I am getting the following:

```
WARNING: error in websocket handler
io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:5
```
From this request:

```clj
{:remote-addr "192.168.0.101",
 :params {},
 :route-params {},
 :headers
 {"host" "192.168.0.100",
  "upgrade" "websocket",
  "user-agent" "arduino-WebSocket-Client",
  "sec-websocket-protocol" "arduino",
  "connection" "Upgrade",
  "sec-websocket-key" "i8CA6i/CaJ2D/TgcvnJs5w==",
  "sec-websocket-version" "13"},
 :server-port 3000,
 :form-params {},
 :compojure/route [:get "/device"],
 :keep-alive? true,
 :query-params {},
 :uri "/device",
 :server-name "192.168.0.100",
 :query-string nil,
 :body nil,
 :scheme :http,
 :request-method :get}
```
I stumbled on this issue from searching: https://github.com/netty/netty/issues/2953 But it doesn't look like it fits, as there are no Extensions specified in the request?

I am trying to establish a WebSocket connection via the following Arduino/esp8266 library: https://github.com/Links2004/arduinoWebSockets

This has stumped me for a while now, as I am not sure how to debug this further. I compared the request from your WebSocket example, and the request above. The only thing different is that I have:

```clj
  "sec-websocket-protocol" "arduino",
  "user-agent" "arduino-WebSocket-Client",
```

And you have:

```clj
  "sec-websocket-origin" "http://localhost:3000"
```

Is this something that I should be asking in the Netty issues?

Thanks

**Comment by ztellman** [comment]
What's the full stack trace?

**Comment by BorisKourt** [comment]
Here it is, as well as the code I am using.

```
WARNING: error in websocket handler
io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:5
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:188)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:744)

```

```clj
(ns server.core
  (:require
    [compojure.core :as compojure :refer [GET]]
    [ring.middleware.params :as params]
    [compojure.route :as route]
    [aleph.http :as http :refer [start-server]]
    [manifold.stream :as s]
    [manifold.deferred :as d]
    [clojure.pprint :refer [pprint]]))


(def non-websocket-request
  {:status  400
   :headers {"content-type" "application/text"}
   :body    "Expected a websocket request."})

(defn printers [ins]
  (println (str ins)))

(defn device-handler
  "This is another asynchronous handler, but uses `let-flow` instead of `chain` to define the
   handler in a way that at least somewhat resembles the synchronous handler."
  [req]
  (pprint req)
  (->
    (d/let-flow [socket (http/websocket-connection req)]
                (s/consume printers socket))
    (d/catch
      (fn [_]
        non-websocket-request))))

(def handler
  (params/wrap-params
    (compojure/routes
      (GET "/device" [] device-handler)
      (route/not-found "No such page."))))

;; (def s (http/start-server handler {:port 3000}))
```

**Comment by ztellman** [comment]
Yeah, I think this is best posted to the Netty issues.

**Comment by BorisKourt** [comment]
Okay, thanks for looking at it!

**Comment by BorisKourt** [comment]
@ztellman They got back to me advising that I "configure your WebSocketServerHandshakerFactory to allow extensions." Is there a way I can set this in Aleph?

**Comment by BorisKourt** [comment]
Thank you!
