### ISSUE TITLE
ByteBuf refCnt issue reading large request body raw-stream

### ISSUE THREAD

**Issue by mfikes** [ztellman/aleph#229]
When reading a large HTTP request body using Aleph, with `:raw-stream? true`, I get a refCnt issue with the latest Aleph betas.

To reproduce (this is on OS X):

`lein new aleph-test` and then add `[aleph "0.4.1-beta6"]` as a `:dependency`

Then `lein repl` and issue the following forms:

```
(require '[aleph.http :as http]
         '[byte-streams :as bs])

(defn handler [req]
  (while (not (neg? (.read (bs/to-input-stream (:body req))))))
  {:status 400})

(http/start-server handler {:port 8081 :raw-stream? true})
```

In a separate terminal:

```
dd if=/dev/zero of=file.txt count=1024 bs=1024
curl -F file=@file.txt http://localhost:8081
```

You will get the following in the REPL:

```
Mar 26, 2016 12:35:20 PM clojure.tools.logging$eval420$fn__424 invoke
SEVERE: error in stream handler
io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1358)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1304)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.nioBuffer(PooledUnsafeDirectByteBuf.java:324)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.nioBuffers(PooledUnsafeDirectByteBuf.java:319)
	at io.netty.buffer.SlicedByteBuf.nioBuffers(SlicedByteBuf.java:320)
	at io.netty.buffer.AbstractByteBuf.nioBuffers(AbstractByteBuf.java:1136)
	at aleph.netty$buf__GT_array.invokeStatic(netty.clj:95)
	at aleph.netty$buf__GT_array.invoke(netty.clj:93)
	at aleph.netty$eval6223$f__5712__auto____6224.invoke(netty.clj:116)
	at byte_streams.graph$conversion_fn$fn__5122$fn__5123.invoke(graph.clj:259)
	at clojure.lang.PersistentUnrolledVector$Card2.reduce(PersistentUnrolledVector.java:478)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at byte_streams.graph$conversion_fn$fn__5122.invoke(graph.clj:253)
	at byte_streams$convert.invokeStatic(byte_streams.clj:193)
	at byte_streams$convert.invoke(byte_streams.clj:162)
	at byte_streams.graph$seq_conversion_fn$fn__5145$fn__5154.invoke(graph.clj:314)
	at manifold.stream$map$fn__4442.invoke(stream.clj:580)
	at manifold.stream.Callback.put(stream.clj:453)
	at manifold.stream.graph$async_send.invokeStatic(graph.clj:50)
	at manifold.stream.graph$async_send.invoke(graph.clj:46)
	at manifold.stream.graph$async_connect$this__3795.invoke(graph.clj:212)
	at manifold.stream.graph$async_connect$this__3795.invoke(graph.clj:160)
	at clojure.core$trampoline.invokeStatic(core.clj:6064)
	at clojure.core$trampoline.invoke(core.clj:6053)
	at manifold.stream.graph$async_connect$this__3795$fn__3800.invoke(graph.clj:188)
	at manifold.deferred.Listener.onSuccess(deferred.clj:219)
	at manifold.deferred.Deferred$fn__2345$fn__2346.invoke(deferred.clj:398)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__1740$f__1741.invoke(executor.clj:36)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```

You don't get this if you instead set `raw-stream? false`

**Comment by ztellman** [comment]
Thanks for the report, I'll take a look.

**Comment by ztellman** [comment]
Oh, ha.  This took me a little too long to notice: you're calling `bs/to-input-stream` repeatedly within the `while` loop, which isn't what should be happening.

This will work fine:

```clj
(defn handler [req]
  (let [body (bs/to-input-stream (:body req))]
    (while (not (neg? (.read body))))
  {:status 400})
```

**Comment by mfikes** [comment]
Thanks Zack. Sorry for wasting your precious time. I owe you a been and an apology.

**Comment by ztellman** [comment]
No worries!  The other issue seem to be a legit memory leak, still digging into it.
