### ISSUE TITLE
No matching method: setLevel thrown when used with fernet-clj

### ISSUE THREAD

**Issue by derwolfe** [ztellman/aleph#247]
I recently released a new version of [fernet-clj](https://github.com/derwolfe/fernet-clj) and have bumped the dependency for it in a consuming library [cloudpassage-lib](https://github.com/racksec/cloudpassage-lib) to use the new version. After modifying the `cloudpassage-lib/project.clj` dependency to `fernet "0.2.0" and running `lein test` the following error is thrown:

```clojure
Exception in thread "main" java.lang.IllegalArgumentException: No matching method: setLevel, compiling:(aleph/netty.clj:62:3)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:589)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler.eval(Compiler.java:6931)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at aleph.http.core$eval4020$loading__5569__auto____4021.invoke(core.clj:1)
	at aleph.http.core$eval4020.invokeStatic(core.clj:1)
	at aleph.http.core$eval4020.invoke(core.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at aleph.http.server$eval4014$loading__5569__auto____4015.invoke(server.clj:1)
	at aleph.http.server$eval4014.invokeStatic(server.clj:1)
	at aleph.http.server$eval4014.invoke(server.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5778)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at aleph.http$eval3169$loading__5569__auto____3170.invoke(http.clj:1)
	at aleph.http$eval3169.invokeStatic(http.clj:1)
	at aleph.http$eval3169.invoke(http.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at cloudpassage_lib.core$eval3163$loading__5569__auto____3164.invoke(core.clj:1)
	at cloudpassage_lib.core$eval3163.invokeStatic(core.clj:1)
	at cloudpassage_lib.core$eval3163.invoke(core.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at cloudpassage_lib.core_test$eval244$loading__5569__auto____245.invoke(core_test.clj:1)
	at cloudpassage_lib.core_test$eval244.invokeStatic(core_test.clj:1)
	at cloudpassage_lib.core_test$eval244.invoke(core_test.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at user$eval143.invokeStatic(form-init6612166575260459099.clj:1)
	at user$eval143.invoke(form-init6612166575260459099.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No matching method: setLevel
	at clojure.lang.Compiler$StaticMethodExpr.<init>(Compiler.java:1642)
	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:1011)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	... 201 more
Tests failed.
```

**Comment by ztellman** [comment]
Sounds like a version collision.  Can you give me the full output of `lein deps :tree`?

**Comment by derwolfe** [comment]
```
Chris@juniper ~/C/cloudpassage-lib (bump)> lein deps :tree
Possibly confusing dependencies found:
[lein-release "1.0.9"] -> [org.clojure/clojure "1.3.0"]
 overrides
[org.clojars.lvh/lein-dash "0.1.2-SNAPSHOT"] -> [lein-codox "0.9.4"] -> [leinjacker "0.4.2"] -> [org.clojure/core.contracts "0.0.1"] -> [org.clojure/core.unify "0.5.3"] -> [org.clojure/clojure "1.4.0"]
 and
[org.clojars.lvh/lein-dash "0.1.2-SNAPSHOT"] -> [lein-codox "0.9.4"] -> [leinjacker "0.4.2"] -> [org.clojure/core.contracts "0.0.1"] -> [org.clojure/clojure "1.4.0"]
 and
[org.clojars.lvh/lein-dash "0.1.2-SNAPSHOT"] -> [yesql "0.5.2"] -> [org.clojure/java.jdbc "0.4.2"] -> [org.clojure/clojure "1.4.0"]
 and
[lein-cljfmt "0.3.0"] -> [cljfmt "0.3.0"] -> [rewrite-clj "0.4.12"] -> [org.clojure/clojure "1.6.0" :exclusions [org.clojure/clojure]]
 and
[lein-bikeshed "0.3.0"] -> [org.clojure/tools.namespace "0.2.6"] -> [org.clojure/clojure "1.4.0"]
 and
[lein-bikeshed "0.3.0"] -> [org.clojure/tools.cli "0.3.1"] -> [org.clojure/clojure "1.4.0"]
 and
[org.clojars.lvh/lein-dash "0.1.2-SNAPSHOT"] -> [yesql "0.5.2"] -> [org.clojure/clojure "1.6.0"]
 and
[lein-ancient "0.6.8"] -> [org.clojure/tools.reader "0.10.0"] -> [org.clojure/clojure "1.4.0"]
 and
[lein-ancient "0.6.8"] -> [jansi-clj "0.1.0"] -> [org.clojure/clojure "1.5.1"]
 and
[lein-ancient "0.6.8"] -> [version-clj "0.1.2"] -> [org.clojure/clojure "1.6.0"]
 and
[lein-ancient "0.6.8"] -> [rewrite-clj "0.4.12"] -> [org.clojure/clojure "1.6.0" :exclusions [org.clojure/clojure]]
 and
[lein-ancient "0.6.8"] -> [ancient-clj "0.3.11" :exclusions [com.amazonaws/aws-java-sdk-s3]] -> [org.clojure/clojure "1.7.0" :exclusions [joda-time org.clojure/clojure]]
 and
[lein-cloverage "1.0.7-SNAPSHOT"] -> [bultitude "0.2.0"] -> [org.clojure/clojure "1.4.0"]
 and
[lein-cljfmt "0.3.0"] -> [meta-merge "0.1.1"] -> [org.clojure/clojure "1.5.1"]
 and
[lein-cljfmt "0.3.0"] -> [cljfmt "0.3.0"] -> [org.clojure/clojure "1.6.0"]
 and
[jonase/eastwood "0.2.3"] -> [org.clojure/clojure "1.5.1"]
 and
[org.clojars.lvh/lein-dash "0.1.2-SNAPSHOT"] -> [org.clojure/clojure "1.8.0"]

Consider using these exclusions:
[org.clojars.lvh/lein-dash "0.1.2-20160406.222249-4" :exclusions [org.clojure/clojure]]
[org.clojars.lvh/lein-dash "0.1.2-20160406.222249-4" :exclusions [org.clojure/clojure]]
[org.clojars.lvh/lein-dash "0.1.2-20160406.222249-4" :exclusions [org.clojure/clojure]]
[lein-cljfmt "0.3.0" :exclusions [org.clojure/clojure]]
[lein-bikeshed "0.3.0" :exclusions [org.clojure/clojure]]
[lein-bikeshed "0.3.0" :exclusions [org.clojure/clojure]]
[org.clojars.lvh/lein-dash "0.1.2-20160406.222249-4" :exclusions [org.clojure/clojure]]
[lein-ancient "0.6.8" :exclusions [org.clojure/clojure]]
[lein-ancient "0.6.8" :exclusions [org.clojure/clojure]]
[lein-ancient "0.6.8" :exclusions [org.clojure/clojure]]
[lein-ancient "0.6.8" :exclusions [org.clojure/clojure]]
[lein-ancient "0.6.8" :exclusions [org.clojure/clojure]]
[lein-cloverage "1.0.7-20150722.142220-11" :exclusions [org.clojure/clojure]]
[lein-cljfmt "0.3.0" :exclusions [org.clojure/clojure]]
[lein-cljfmt "0.3.0" :exclusions [org.clojure/clojure]]
[jonase/eastwood "0.2.3" :exclusions [org.clojure/clojure]]
[org.clojars.lvh/lein-dash "0.1.2-20160406.222249-4" :exclusions [org.clojure/clojure]]

 [aleph "0.4.1-beta2"]
   [byte-streams "0.2.1-alpha1"]
     [clj-tuple "0.2.2"]
     [primitive-math "0.1.4"]
   [io.netty/netty-all "4.1.0.Beta6"]
   [potemkin "0.4.1"]
 [base64-clj "0.1.1"]
 [camel-snake-kebab "0.3.2"]
 [cheshire "5.5.0"]
   [com.fasterxml.jackson.core/jackson-core "2.5.3"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.5.3"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.5.3"]
   [tigris "0.1.1"]
 [clj-time "0.11.0"]
   [joda-time "2.8.2"]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [com.cemerick/url "0.1.1"]
   [pathetic "0.5.0"]
     [com.cemerick/clojurescript.test "0.0.4"]
       [org.clojure/clojurescript "0.0-1586"]
         [com.google.javascript/closure-compiler "r2180"]
           [args4j "2.0.16"]
           [com.google.code.findbugs/jsr305 "1.3.9"]
           [com.google.guava/guava "13.0.1"]
           [com.google.protobuf/protobuf-java "2.4.1"]
           [com.googlecode.jarjar/jarjar "1.1"]
           [org.apache.ant/ant "1.8.2"]
             [org.apache.ant/ant-launcher "1.8.2"]
           [org.json/json "20090211"]
         [org.clojure/google-closure-library "0.0-2029-2"]
           [org.clojure/google-closure-library-third-party "0.0-2029-2"]
         [org.mozilla/rhino "1.7R4"]
 [com.taoensso/carmine "2.12.1"]
   [com.taoensso/nippy "2.10.0"]
     [net.jpountz.lz4/lz4 "1.3"]
     [org.iq80.snappy/snappy "0.4"]
     [org.tukaani/xz "1.5"]
   [commons-codec "1.10"]
   [org.apache.commons/commons-pool2 "2.4.2"]
   [org.clojure/data.json "0.2.6"]
 [com.taoensso/timbre "4.2.0"]
   [com.taoensso/encore "2.31.3"]
     [org.clojure/tools.reader "0.10.0"]
   [io.aviso/pretty "0.1.20"]
 [environ "1.0.1"]
 [fernet "0.2.0"]
   [clojurewerkz/buffy "0.3.0"]
     [io.netty/netty-buffer "4.0.12.Final"]
       [io.netty/netty-common "4.0.12.Final"]
     [reiddraper/simple-check "0.5.3"]
   [org.bouncycastle/bcprov-jdk15on "1.49"]
 [manifold "0.1.4"]
   [io.aleph/dirigiste "0.1.3"]
   [org.clojure/tools.logging "0.3.1" :exclusions [[org.clojure/clojure]]]
   [riddley "0.1.12"]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/math.numeric-tower "0.0.4"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [pjstadig/humane-test-output "0.7.1"]
 [slamhound "1.5.5"]
```

**Comment by derwolfe** [comment]
I've gone through and whittled down the dependencies in my `~/.lein/profiles.clj`file. `lein deps :tree` is no longer providing any warnings. Here is the output:

```clojure
Chris@juniper ~/C/cloudpassage-lib (bump)> lein deps :tree
 [aleph "0.4.1-beta2"]
   [byte-streams "0.2.1-alpha1"]
     [clj-tuple "0.2.2"]
     [primitive-math "0.1.4"]
   [io.netty/netty-all "4.1.0.Beta6"]
   [potemkin "0.4.1"]
 [base64-clj "0.1.1"]
 [camel-snake-kebab "0.3.2"]
 [cheshire "5.5.0"]
   [com.fasterxml.jackson.core/jackson-core "2.5.3"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.5.3"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.5.3"]
   [tigris "0.1.1"]
 [clj-time "0.11.0"]
   [joda-time "2.8.2"]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [com.cemerick/url "0.1.1"]
   [pathetic "0.5.0"]
     [com.cemerick/clojurescript.test "0.0.4"]
       [org.clojure/clojurescript "0.0-1586"]
         [com.google.javascript/closure-compiler "r2180"]
           [args4j "2.0.16"]
           [com.google.code.findbugs/jsr305 "1.3.9"]
           [com.google.guava/guava "13.0.1"]
           [com.google.protobuf/protobuf-java "2.4.1"]
           [com.googlecode.jarjar/jarjar "1.1"]
           [org.apache.ant/ant "1.8.2"]
             [org.apache.ant/ant-launcher "1.8.2"]
           [org.json/json "20090211"]
         [org.clojure/google-closure-library "0.0-2029-2"]
           [org.clojure/google-closure-library-third-party "0.0-2029-2"]
         [org.mozilla/rhino "1.7R4"]
 [com.taoensso/carmine "2.12.1"]
   [com.taoensso/nippy "2.10.0"]
     [net.jpountz.lz4/lz4 "1.3"]
     [org.iq80.snappy/snappy "0.4"]
     [org.tukaani/xz "1.5"]
   [commons-codec "1.10"]
   [org.apache.commons/commons-pool2 "2.4.2"]
   [org.clojure/data.json "0.2.6"]
 [com.taoensso/timbre "4.2.0"]
   [com.taoensso/encore "2.31.3"]
     [org.clojure/tools.reader "0.10.0"]
   [io.aviso/pretty "0.1.20"]
 [environ "1.0.1"]
 [fernet "0.2.0"]
   [clojurewerkz/buffy "0.3.0"]
     [io.netty/netty-buffer "4.0.12.Final"]
       [io.netty/netty-common "4.0.12.Final"]
     [reiddraper/simple-check "0.5.3"]
   [org.bouncycastle/bcprov-jdk15on "1.49"]
 [manifold "0.1.4"]
   [io.aleph/dirigiste "0.1.3"]
   [org.clojure/tools.logging "0.3.1" :exclusions [[org.clojure/clojure]]]
   [riddley "0.1.12"]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/math.numeric-tower "0.0.4"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [pjstadig/humane-test-output "0.7.1"]
 [slamhound "1.5.5"]
```
The error generated by `lein test` has remained the same.

**Comment by ztellman** [comment]
You'll need to exclude `io.netty/netty-buffer` from `fernet.

**Comment by derwolfe** [comment]
@ztellman Thank you for your help! :-)
