### ISSUE TITLE
Indefinite blocking when passing a nil header

### ISSUE THREAD

**Issue by Deltanic** [ztellman/aleph#271]
Using a nil HTTP header results in an indefinitely running request (unless a timeout is met).
Code in question:
```
@(http/get "http://ip.jsontest.com" {:headers {"foo" nil}}))
```

This behavior is present on the current master (9cdd682). Anyone has a view on this?

**Comment by ztellman** [comment]
When I run this I get this error logged:

```
SEVERE: error in stream handler
java.lang.IllegalArgumentException: nil value for header key 'Foo'
	at aleph.http.core$map__GT_headers_BANG_.invokeStatic(core.clj:136)
	at aleph.http.core$map__GT_headers_BANG_.invoke(core.clj:129)
	at aleph.http.core$ring_request__GT_netty_request.invokeStatic(core.clj:164)
	at aleph.http.core$ring_request__GT_netty_request.invoke(core.clj:155)
	at aleph.http.client$http_connection$fn__10528$fn__10529.invoke(client.clj:310)
	at manifold.stream.Callback.put(stream.clj:454)
	at manifold.stream.graph$async_send.invokeStatic(graph.clj:78)
	at manifold.stream.graph$async_send.invoke(graph.clj:74)
	at manifold.stream.graph$async_connect$this__5166.invoke(graph.clj:209)
	at manifold.stream.graph$async_connect$this__5166$fn__5167$fn__5168.invoke(graph.clj:190)
	at clojure.core$trampoline.invokeStatic(core.clj:6064)
	at clojure.core$trampoline.invoke(core.clj:6053)
	at manifold.stream.graph$async_connect$this__5166$fn__5167.invoke(graph.clj:190)
	at manifold.deferred.Listener.onSuccess(deferred.clj:219)
	at manifold.deferred.Deferred$fn__4562.invoke(deferred.clj:398)
	at manifold.deferred.Deferred.success(deferred.clj:398)
	at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:245)
	at manifold.deferred$success_BANG_.invoke(deferred.clj:240)
	at manifold.stream.default.Stream.put(default.clj:119)
	at manifold.stream.default.Stream.put(default.clj:141)
	at aleph.http.client$http_connection$fn__10528$fn__10541$fn__10542.invoke(client.clj:334)
	at aleph.http.client$http_connection$fn__10528$fn__10541.invoke(client.clj:333)
	at aleph.http.client_middleware$wrap_exceptions$fn__10210$fn__10220.invoke(client_middleware.clj:223)
	at manifold.deferred$eval4708$chain_SINGLEQUOTE____4729.invoke(deferred.clj:752)
	at aleph.http.client_middleware$wrap_exceptions$fn__10210.invoke(client_middleware.clj:223)
	at aleph.http.client_middleware$wrap_request_timing$fn__10340.invoke(client_middleware.clj:519)
	at aleph.http.client_middleware$wrap_request$fn__10431.invoke(client_middleware.clj:633)
	at aleph.http$eval10615$request__10619$fn__10621$fn__10622$fn__10625.invoke(http.clj:233)
	at manifold.deferred$eval4708$chain_SINGLEQUOTE____4729.invoke(deferred.clj:770)
	at manifold.deferred$eval4708$subscribe__4709$fn__4718.invoke(deferred.clj:724)
	at manifold.deferred.Listener.onSuccess(deferred.clj:219)
	at manifold.deferred.Deferred$fn__4554$fn__4555.invoke(deferred.clj:396)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$3.run(Executor.java:308)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__3957$f__3958.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```

However, it's a bug that this isn't being surfaced as a error response.  I'll take care of that.
