### ISSUE TITLE
max frame length seems ignored on http/websocket-client

### ISSUE THREAD

**Issue by eslachance** [ztellman/aleph#291]
I'm receiving *very* large packets through a websocket and I'm having trouble getting the websocket-client to accept them. I have the following code: 

```clj
@(http/websocket-client "wss://gateway.discord.gg/?v=6&encoding=json"
                                   {:max-frame-payload 65556
                                    :max-frame-size 65556
                                    :max-queue-size 65556})
```

(I did a small change only, to ensure I wasn't causing any other error). The error still says the wrong size, however: `io.netty.handler.codec.CorruptedFrameException: Max frame length of 65536 has been exceeded.` , so I'm not sure how to resolve this. 

Here is the *complete* stack trace: 
```
[aleph-netty-client-event-pool-1-1] WARN aleph.http.client - error in websocket client
io.netty.handler.codec.CorruptedFrameException: Max frame length of 65536 has been exceeded.
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:277)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1052)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:895)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ztellman** [comment]
The `:max-frame-payload` doesn't automatically split your binary payloads, it just enforces a limit, which is why you're seeing an error.  Since WebSockets are not a streaming protocol, it's unlikely that all, or even most, uses of WebSockets would be robust to this sort of auto-splitting.  If you want to sub-divide, you my try something like:

```clj
(s/put-all! socket (byte-streams/to-byte-buffers payload {:chunk-size 65536})
```

**Comment by eslachance** [comment]
I'm not *sending* a packet though. I'm *receiving* it, I have no control over how this packet is built or how it's transmitted.

**Comment by ztellman** [comment]
I see, I'm sorry for misunderstanding your original issue.  I'll double-check that the `:max-frame-payload` is being sent to the server, but it's entirely possible that the server is simply not honoring that parameter, causing Netty to throw a validation error.

**Comment by eslachance** [comment]
Thank you, I appreciate it. This is kind of a bit blocker for me though - if this doesn't work I'll have to attempt switching to another websocket library, and I've already gone though 2 :(

**Comment by ztellman** [comment]
Just to be clear, you can't just set the frame size arbitrarily large on
your end? The protocol allows for more or less arbitrary sizes.

**Comment by eslachance** [comment]
I tried to set all 3 values to a different number and it doesn't seem to affect the error message in any way (or resolve the issue). And I mean I tried to put the numbers to `67108864` which is obviously immense, but it didn't seem to change anything at all.

**Comment by ztellman** [comment]
So when you increase `:max-frame-size` to something like `1e6` that doesn't change the value in the exception you see?  I'm looking at the code now, and I think it was a mistake to make `:max-payload-size` an explicit parameter rather than something derived from `:max-frame-size`. As an experiment, please set `:max-frame-size` to `2e6` and `:max-payload-size` to `1e6`, and see what happens.

**Comment by eslachance** [comment]
Unfortunately, that doesn't seem to change anything either - also I assumed you meant `:max-frame-payload` , but I tried both just in case.

**Comment by ztellman** [comment]
Yes, sorry for the confusion there.  Can you provide a reproducing case for this?  I've tried simply connecting to the gateway, as provided, and don't see any issues.

**Comment by eslachance** [comment]
Reproducing this issue is... well a little difficult considering it requires a Discord account that's on a large server. The large packets are only sent after you've authenticated and setup a heartbeat timer. If you're willing, however: 

- In Chrome, click here: [Discord API](https://discord.gg/discord-api) , and create an account. You'll be on the Discord API server. 
- Access the console (CTRL+SHIFT+I), go to the Applications tab, click on discordapp.com on the left under Local Storage. 
- On the right, copy the Token string

Next you'll need to actually start the project: 
- `git pull eslachance/dithcord` , to grab the current project. 
- Open REPL for the project
- Run the following code, which *should* display the issue (change the state's `:token` keyword to the one you got from the browser):

```clj
(defn debug [s d]
  (prn (str "[" (str (java.util.Date.)) "][DEBUG]" d)))
(def handlers {:debug [debug]})
(def state {:token "enter-user-token-here"
            :handlers handlers})
(def session (connect state)
```

You can see the websocket client being generated on line 135 of `src/dithcord/core.clj`

> Please excuse this mess of a project - I'm new to clojure I'm doing my best!

**Comment by eslachance** [comment]
Also, I'm on Clojurians, if you want to continue troubleshooting there I'm available.

**Comment by eslachance** [comment]
I feel a little bad, I was on version 0.4.1 , which is the one in the readme, I didn't think of getting the latest. Everything works fine on `[aleph "0.4.2-alpha12"]` . I apologize for wasting your time!

**Comment by ztellman** [comment]
No worries, it's far past time for me to release a new version, this is
just more motivation. Thanks for the update.
