### ISSUE TITLE
 1000并发 1000 concurrent java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by xingzhefeng** [ztellman/aleph#295]
```
[2017-02-18 11:02:28,227][ERROR][manifold.deferred] error in deferred handler
java.util.concurrent.RejectedExecutionException
        at io.aleph.dirigiste.Executor.execute(Executor.java:332)
        at manifold.deferred.Deferred$fn__1121.invoke(deferred.clj:395)
        at manifold.deferred.Deferred.success(deferred.clj:395)
        at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:243)
        at manifold.deferred$success_BANG_.invoke(deferred.clj:240)
        at aleph.http.server$eval13056$send_response__13061$fn__13068.invoke(server.clj:119)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ztellman** [comment]
If you use the default executor, too many concurrent requests will return a
503 with that status code. If you'd like to avoid this, consider specifying
:none or an executor with more threads.

**Comment by xingzhefeng** [comment]
thank you very much.
Can you give me an example? 
Tell me exactly what to do.

**Comment by xsc** [comment]
@xingzhefeng You can supply a [`java.util.concurrent.Executor`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executor.html) to `aleph.http/start-server`([see its docstring](https://github.com/ztellman/aleph/blob/master/src/aleph/http.clj#L30)). For example, a [fixed size one](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newFixedThreadPool-int-):

```clojure
(java.util.concurrent.Executors/newFixedThreadPool 16)
```

Which can then be used on server startup using the `:executor` key:

```clojure
(aleph.http/start-server ... {:executor ...})
```

There are multiple executor variants, not all suited for all use cases – it's important to understand the differences.

**Comment by xingzhefeng** [comment]
thank you very much.@xsc
