### ISSUE TITLE
NoClassDefFoundError when shutting down server

### ISSUE THREAD

**Issue by jsyrjala** [ztellman/aleph#320]
Sometimes when I shut down the server I get this stacktrace. It happens maybe about 50% of time.

Here is a Netty issue that seems related https://github.com/netty/netty/issues/6596

I am using `[aleph "0.4.3"]` with `[yada "1.2.2"]` and `[bidi "2.0.17"]`.

```
Exception in thread "shutdown-thread" java.lang.NoClassDefFoundError: io/netty/channel/AbstractChannelHandlerContext$13
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:610)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465)
        at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:964)
        at io.netty.channel.AbstractChannel.close(AbstractChannel.java:234)
        at aleph.netty$start_server$reify__13769.close(netty.clj:779)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
        at yada.aleph$listener$fn__18000.invoke(aleph.clj:17)
        at suosittelukone_query_server.server$stop_server.invokeStatic(server.clj:165)
        at suosittelukone_query_server.server$stop_server.invoke(server.clj:161)
        at suosittelukone_query_server.core$_main$fn__23380.invoke(core.clj:53)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.AbstractChannelHandlerContext$13
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more
```

**Comment by ztellman** [comment]
You're probably relying on the wrong version of Netty. What's the output of
'lein deps :tree'?

**Comment by jsyrjala** [comment]
Only netty related thing I see is ` [io.netty/netty-all "4.1.9.Final"]` which comes from aleph.

````
Possibly confusing dependencies found:
[bidi "2.0.17"] -> [ring/ring-core "1.5.0" :exclusions [org.clojure/tools.reader org.clojure/clojure]]
 overrides
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/webjars "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/bidi "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/jwt "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/json "1.2.2" :exclusions [commons-codec]] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/jwt "1.2.2" :exclusions [commons-codec]] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/webjars "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/transit "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/core "1.2.2" :exclusions [commons-codec]] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/core "1.2.2" :exclusions [commons-codec]] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/multipart "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/jwt "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/json-html "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/json "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/bidi "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/async "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/aleph "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]
[yada "1.2.2" :exclusions [ring/ring-core]]

[midje "1.8.3"] -> [clj-time "0.11.0" :exclusions [org.clojure/clojure]]
 overrides
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/webjars "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/bidi "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/jwt "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/json "1.2.2" :exclusions [commons-codec]] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/jwt "1.2.2" :exclusions [commons-codec]] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/webjars "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/transit "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [metosin/ring-swagger "0.22.12" :exclusions [org.clojure/clojure]] -> [clj-time "0.12.1"]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/core "1.2.2" :exclusions [commons-codec]] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/core "1.2.2" :exclusions [commons-codec]] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/multipart "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/jwt "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/json-html "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/json "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/bidi "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/async "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/aleph "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]
 and
[yada "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]
[yada "1.2.2" :exclusions [clj-time]]

[clj-http "3.5.0"] -> [potemkin "0.4.3" :exclusions [org.clojure/clojure]] -> [riddley "0.1.12"]
 overrides
[aleph "0.4.3"] -> [manifold "0.1.6"] -> [riddley "0.1.14"]

Consider using these exclusions:
[aleph "0.4.3" :exclusions [riddley]]

[bidi "2.0.17"] -> [ring/ring-core "1.5.0" :exclusions [org.clojure/tools.reader org.clojure/clojure]] -> [commons-fileupload "1.3.1"]
 overrides
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/webjars "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/bidi "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/jwt "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/json "1.2.2" :exclusions [commons-codec]] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/jwt "1.2.2" :exclusions [commons-codec]] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/webjars "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/transit "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/core "1.2.2" :exclusions [commons-codec]] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/core "1.2.2" :exclusions [commons-codec]] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/multipart "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/jwt "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/json-html "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/json "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/bidi "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/async "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/aleph "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]
 and
[yada "1.2.2"] -> [yada/core "1.2.2"] -> [ring/ring-core "1.6.0-beta6" :exclusions [org.clojure/clojure]] -> [commons-fileupload "1.3.2"]

Consider using these exclusions:
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]
[yada "1.2.2" :exclusions [commons-fileupload]]

[midje "1.8.3"] -> [clj-time "0.11.0" :exclusions [org.clojure/clojure]] -> [joda-time "2.8.2"]
 overrides
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/webjars "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/bidi "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/jwt "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/json "1.2.2" :exclusions [commons-codec]] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/jwt "1.2.2" :exclusions [commons-codec]] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/webjars "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/transit "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [metosin/ring-swagger "0.22.12" :exclusions [org.clojure/clojure]] -> [clj-time "0.12.1"] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/swagger "1.2.2"] -> [yada/core "1.2.2" :exclusions [commons-codec]] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/oauth2 "1.2.2"] -> [yada/core "1.2.2" :exclusions [commons-codec]] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/multipart "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/jwt "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/json-html "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/json "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/bidi "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/async "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/aleph "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]
 and
[yada "1.2.2"] -> [yada/core "1.2.2"] -> [clj-time "0.12.2" :exclusions [org.clojure/clojure]] -> [joda-time "2.9.4"]

Consider using these exclusions:
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]
[yada "1.2.2" :exclusions [joda-time]]

 [aleph "0.4.3"]
   [byte-streams "0.2.2"]
     [primitive-math "0.1.5"]
   [io.netty/netty-all "4.1.9.Final"]
   [manifold "0.1.6"]
     [io.aleph/dirigiste "0.1.5"]
 [bidi "2.0.17"]
   [ring/ring-core "1.5.0" :exclusions [[org.clojure/tools.reader] [org.clojure/clojure]]]
     [commons-fileupload "1.3.1"]
     [crypto-equality "1.0.0"]
     [crypto-random "1.2.0"]
     [ring/ring-codec "1.0.1"]
 [camel-snake-kebab "0.4.0"]
 [ch.qos.logback/logback-classic "1.2.3"]
   [ch.qos.logback/logback-core "1.2.3"]
 [cheshire "5.7.1"]
   [com.fasterxml.jackson.core/jackson-core "2.8.6"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.8.6"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.8.6"]
   [tigris "0.1.1"]
 [clj-http "3.5.0"]
   [commons-codec "1.10" :exclusions [[org.clojure/clojure]]]
   [commons-io "2.5" :exclusions [[org.clojure/clojure]]]
   [org.apache.httpcomponents/httpasyncclient "4.1.3" :exclusions [[org.clojure/clojure]]]
     [org.apache.httpcomponents/httpcore-nio "4.4.6"]
   [org.apache.httpcomponents/httpclient "4.5.3" :exclusions [[org.clojure/clojure]]]
     [commons-logging "1.2"]
   [org.apache.httpcomponents/httpcore "4.4.6" :exclusions [[org.clojure/clojure]]]
   [org.apache.httpcomponents/httpmime "4.5.3" :exclusions [[org.clojure/clojure]]]
   [potemkin "0.4.3" :exclusions [[org.clojure/clojure]]]
     [clj-tuple "0.2.2"]
     [riddley "0.1.12"]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [com.climate/claypoole "1.1.4"]
 [com.stuartsierra/component "0.3.2"]
   [com.stuartsierra/dependency "0.2.0"]
 [environ "1.1.0"]
 [midje "1.8.3" :scope "test"]
   [clj-time "0.11.0" :exclusions [[org.clojure/clojure]]]
     [joda-time "2.8.2"]
   [colorize "0.1.1" :scope "test" :exclusions [[org.clojure/clojure]]]
   [flare "0.2.9" :scope "test" :exclusions [[org.clojure/clojure]]]
     [org.clojars.brenton/google-diff-match-patch "0.1" :scope "test"]
   [marick/clojure-commons "1.1.3" :scope "test" :exclusions [[org.clojure/clojure]]]
   [marick/suchwow "4.4.3" :scope "test" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
     [com.rpl/specter "0.9.0" :scope "test" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
   [ordered "1.2.0" :scope "test" :exclusions [[org.clojure/clojure]]]
   [org.clojure/core.unify "0.5.2" :scope "test" :exclusions [[org.clojure/clojure]]]
   [org.clojure/math.combinatorics "0.1.1" :scope "test"]
   [org.clojure/tools.macro "0.1.5" :scope "test"]
   [org.tcrawley/dynapath "0.2.3" :scope "test"]
   [swiss-arrows "1.0.0" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/core.cache "0.6.5"]
   [org.clojure/data.priority-map "0.0.7"]
 [org.clojure/core.memoize "0.5.9"]
 [org.clojure/tools.cli "0.3.5"]
 [org.clojure/tools.logging "0.3.1"]
 [org.clojure/tools.namespace "0.2.11" :scope "test"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [org.slf4j/jcl-over-slf4j "1.7.25"]
 [org.slf4j/log4j-over-slf4j "1.7.25"]
 [org.slf4j/slf4j-api "1.7.25"]
 [prismatic/schema "1.1.5"]
 [reloaded.repl "0.2.3" :scope "test"]
   [suspendable "0.1.1" :scope "test"]
 [slingshot "0.12.2"]
 [yada "1.2.2"]
   [yada/aleph "1.2.2"]
   [yada/async "1.2.2"]
     [org.clojure/core.async "0.2.395"]
       [org.clojure/tools.analyzer.jvm "0.6.10"]
         [org.clojure/tools.analyzer "0.6.9"]
         [org.ow2.asm/asm-all "4.2"]
   [yada/bidi "1.2.2"]
   [yada/core "1.2.2"]
     [hiccup "1.0.5" :exclusions [[org.clojure/clojure]]]
     [org.clojure/data.codec "0.1.0" :exclusions [[org.clojure/clojure]]]
     [org.clojure/tools.reader "1.0.0-beta4" :exclusions [[org.clojure/clojure]]]
   [yada/json-html "1.2.2"]
     [json-html "0.4.0" :exclusions [[hiccups]]]
   [yada/json "1.2.2"]
   [yada/jwt "1.2.2"]
     [buddy/buddy-sign "1.3.0"]
       [buddy/buddy-core "1.1.1"]
         [org.bouncycastle/bcpkix-jdk15on "1.55"]
         [org.bouncycastle/bcprov-jdk15on "1.55"]
   [yada/multipart "1.2.2"]
   [yada/oauth2 "1.2.2"]
   [yada/swagger "1.2.2"]
     [metosin/ring-swagger "0.22.12" :exclusions [[org.clojure/clojure]]]
       [frankiesardo/linked "1.2.9"]
       [metosin/ring-http-response "0.8.0"]
       [metosin/schema-tools "0.9.0"]
       [metosin/scjsv "0.4.0"]
         [com.github.fge/json-schema-validator "2.2.6"]
           [com.github.fge/json-schema-core "1.2.5"]
             [com.github.fge/jackson-coreutils "1.8"]
             [com.github.fge/uri-template "0.9"]
               [com.github.fge/msg-simple "1.1"]
                 [com.github.fge/btf "1.2"]
               [com.google.guava/guava "16.0.1"]
             [org.mozilla/rhino "1.7R4"]
           [com.google.code.findbugs/jsr305 "3.0.0"]
           [com.googlecode.libphonenumber/libphonenumber "6.2"]
           [javax.mail/mailapi "1.4.3"]
             [javax.activation/activation "1.1"]
           [net.sf.jopt-simple/jopt-simple "4.6"]
       [org.tobereplaced/lettercase "1.0.0"]
       [prismatic/plumbing "0.5.3"]
         [de.kotka/lazymap "3.1.0" :exclusions [[org.clojure/clojure]]]
     [org.webjars/swagger-ui "2.2.6"]
   [yada/transit "1.2.2"]
     [com.cognitect/transit-clj "0.8.297"]
       [com.cognitect/transit-java "0.8.319"]
         [org.msgpack/msgpack "0.6.12"]
           [com.googlecode.json-simple/json-simple "1.1.1" :exclusions [[junit]]]
           [org.javassist/javassist "3.18.1-GA"]
   [yada/webjars "1.2.2"]
     [org.webjars/webjars-locator "0.32"]
       [com.fasterxml.jackson.core/jackson-databind "2.3.3"]
         [com.fasterxml.jackson.core/jackson-annotations "2.3.0"]
       [org.webjars/webjars-locator-core "0.30"]
         [org.apache.commons/commons-compress "1.9"]
         [org.apache.commons/commons-lang3 "3.1"]
```

**Comment by ztellman** [comment]
Are there any AOT-compiled jars in those dependencies?

**Comment by jsyrjala** [comment]
Not sure, but I am AOT compiling and uberjaring my project (`:profiles {:uberjar { :aot :all } }`) 

````
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [cheshire "5.7.1"]
                 [camel-snake-kebab "0.4.0"]
                 [clj-http "3.5.0"]
                 [environ "1.1.0"]
                 [com.climate/claypoole "1.1.4"]

                 ;; wiring
                 [com.stuartsierra/component "0.3.2"]
                 [prismatic/schema "1.1.5"]
                 [org.clojure/tools.cli "0.3.5"]
                 [slingshot "0.12.2"]
                 [org.clojure/tools.cli "0.3.5"]

                 ;; web
                 [yada "1.2.2"]
                 [aleph "0.4.3"]
                 [bidi "2.0.17"]

                 [org.clojure/core.cache "0.6.5"]
                 [org.clojure/core.memoize "0.5.9"]

                 ;; logging
                 [org.clojure/tools.logging "0.3.1"]
                 [ch.qos.logback/logback-classic "1.2.3"]
                 [org.slf4j/slf4j-api "1.7.25"]
                 [org.slf4j/log4j-over-slf4j "1.7.25"]
                 [org.slf4j/jcl-over-slf4j "1.7.25"]]
```

**Comment by ztellman** [comment]
Okay, at a glance I'm not sure, but can you try `jar xvf` on the `*-standalone.jar` in `target`, and see what's under the `/io/netty` directory?  My guess is that there's an older version of Netty wrapped up in one of your dependencies, but I'm not 100% sure.

**Comment by gsnewmark** [comment]
@jsyrjala are you, by any chance, shutting the server down using the JVM's shutdown hook? Those hooks are started in [undetermined order](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#addShutdownHook-java.lang.Thread-) and it's possible that your code runs after the classes needed for it are already unloaded.

**Comment by jsyrjala** [comment]
@gsnewmark I am shutting down the server inside shutdown hook. I wonder though why the netty classes would be unloaded before shutdown hooks are finished.

**Comment by gsnewmark** [comment]
@jsyrjala it's possible that Netty itself has shutdown hooks which unload classes (didn't check its source), or it can even be some internal JVM process, so sometimes your shutdown works fine (in case your own shutdown hook runs before the class unload) and sometimes it fails. There are [some](https://stackoverflow.com/a/22664836) [hacks](https://bz.apache.org/bugzilla/show_bug.cgi?id=10565#c5) to avoid the problem, but I'm didn't use them in Clojure so can't comment on that.

**Comment by ztellman** [comment]
I'm sorry I don't have more insight into this problem.  If you can provide a reproducing example, I can look into it further.

**Comment by jamesdbloom** [comment]
I am also seeing this problem.  If I add a 2 second sleep to prevent the JVM from stopping after stopping Netty the issue goes away proving this is not at all related to dependencies, as follows:

Errors:

```java
        // Shut down all event loops to terminate all threads.
        bossGroup.shutdownGracefully();
        workerGroup.shutdownGracefully();

        // Wait until all threads are terminated.
        bossGroup.terminationFuture().syncUninterruptibly();
        workerGroup.terminationFuture().syncUninterruptibly();
```

No error:

```java
        // Shut down all event loops to terminate all threads.
        bossGroup.shutdownGracefully();
        workerGroup.shutdownGracefully();

        // Wait until all threads are terminated.
        bossGroup.terminationFuture().syncUninterruptibly();
        workerGroup.terminationFuture().syncUninterruptibly();

        try {
            // ensure that shutdown has actually completed and won't
            // cause class loader error if JVM starts unloading classes
            SECONDS.sleep(2);
        } catch (InterruptedException ignore) {
            // ignore
        }
```
