### ISSUE TITLE
Websocket example doesn't run

### ISSUE THREAD

**Issue by vushu** [ztellman/aleph#416]
When I try to run the example code for websocket from:
https://aleph.io/examples/literate.html#aleph.examples.websocket

I get this following error, any ideas how to resolve this?
```
Sep 17, 2018 6:02:19 PM clojure.tools.logging$eval2857$fn__2860 invoke
SEVERE: error in HTTP handler
java.lang.IllegalArgumentException: No implementation of method: :render of protocol: #'compojure.response/Renderable found for class: java.lang.Boolean
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
        at compojure.response$eval375$fn__376$G__366__383.invoke(response.clj:7)
        at compojure.response$eval461$fn__462.invoke(response.clj:51)
        at compojure.response$eval375$fn__376$G__366__383.invoke(response.clj:7)
        at compojure.response$eval453$fn__454.invoke(response.clj:47)
        at compojure.response$eval375$fn__376$G__366__383.invoke(response.clj:7)
        at compojure.core$wrap_response$fn__2330.invoke(core.clj:158)
        at compojure.core$wrap_route_middleware$fn__2314.invoke(core.clj:128)
        at compojure.core$wrap_route_info$fn__2319.invoke(core.clj:137)
        at compojure.core$wrap_route_matches$fn__2323.invoke(core.clj:146)
        at compojure.core$routing$fn__2338.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__2342.invoke(core.clj:192)
        at ring.middleware.params$wrap_params$fn__2517.invoke(params.clj:67)
        at aleph.http.server$handle_request$fn__17975$f__3203__auto____17976.invoke(server.clj:158)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
        at manifold.executor$thread_factory$reify__3085$f__3086.invoke(executor.clj:44)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ztellman** [comment]
Hi, as far as I can tell the examples were working fine, but Compojure was getting a "response" it didn't recognize in the chat handler after the websocket upgrade had already occurrred.  This should be fixed by https://github.com/ztellman/aleph/commit/09bb2e2e89c648d75e72b3bb2500046324d3db55.
